### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ToBiDi0410** [ToBiDi0410/SpigotFiles#1]
List:
- [x] Make the contextmenu on the Webinterface fancier
- [x] Use DaisyUI for Buttons, Spinners, etc
- [ ] Update Login Page to new UI
- [ ] Add better error handling for actions (show errors in the dialogue)
- [ ] Allow saving files in the viewer
- [ ] Fix downloading files (some files are corrupt after download)
- [ ] Also update index if file size has changed (too much performance decrease?)

Please note that these are only ideas and implementation
may take a long time or will not be done at all

**Comment by ToBiDi0410** [comment]
Working on a new and fancier Webinterface (with Drag&Drop and actions like delete, move and rename)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/40767401/211914336-4d0c43e4-d064-4afb-bbc8-f583e0d129b1.png">

**Comment by ToBiDi0410** [comment]
UI update is now basically done
